name: news_app
description: Ứng dụng đọc tin tức NewsFlow - Đồ án Lập trình Mobile
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9        # Push Notifications (FCM)
  firebase_dynamic_links: ^5.4.5     # Deep Links

  # State Management
  provider: ^6.1.1

  # Local Storage (SQLite)
  sqflite: ^2.3.0
  path: ^1.8.3

  # Networking
  http: ^1.1.2

  # UI
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  share_plus: ^7.2.1
  image_picker: ^1.0.7
  timeago: ^3.6.0
  intl: ^0.19.0
  google_fonts: ^6.1.0

  # Text-to-Speech  (Tính năng 5)
  flutter_tts: ^4.0.2

  # Shared Preferences – lưu theme, font settings  (Tính năng 4 & 6)
  shared_preferences: ^2.2.2

  # Flutter Local Notifications – hiển thị FCM khi app foreground
  flutter_local_notifications: ^17.2.2
  google_generative_ai: ^0.4.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true