// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_6HmkxrGbB-IUqRRKegJoigOm3jeJDzs',
    appId: '1:659145170944:web:a7e16cfcf6b1ac5b95b8e5',
    messagingSenderId: '659145170944',
    projectId: 'newsflow-app-4813a',
    authDomain: 'newsflow-app-4813a.firebaseapp.com',
    storageBucket: 'newsflow-app-4813a.firebasestorage.app',
    measurementId: 'G-RB14XF4CQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0WFoyg5EmxmnUkRhbLiFXuvlCGprWc3Y',
    appId: '1:659145170944:android:7c2dc3ebcf3538e795b8e5',
    messagingSenderId: '659145170944',
    projectId: 'newsflow-app-4813a',
    storageBucket: 'newsflow-app-4813a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxC-_TaStPOWKqytXyU9KhnMRUDeMkPcc',
    appId: '1:659145170944:ios:a427d5f1303e847495b8e5',
    messagingSenderId: '659145170944',
    projectId: 'newsflow-app-4813a',
    storageBucket: 'newsflow-app-4813a.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxC-_TaStPOWKqytXyU9KhnMRUDeMkPcc',
    appId: '1:659145170944:ios:a427d5f1303e847495b8e5',
    messagingSenderId: '659145170944',
    projectId: 'newsflow-app-4813a',
    storageBucket: 'newsflow-app-4813a.firebasestorage.app',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_6HmkxrGbB-IUqRRKegJoigOm3jeJDzs',
    appId: '1:659145170944:web:fa663ee57aadc34e95b8e5',
    messagingSenderId: '659145170944',
    projectId: 'newsflow-app-4813a',
    authDomain: 'newsflow-app-4813a.firebaseapp.com',
    storageBucket: 'newsflow-app-4813a.firebasestorage.app',
    measurementId: 'G-XQKN3YM5T1',
  );
}
